xorm:
  drivename: postgres
  ip: 127.0.0.1
  # port: 3306
  port: 5432
  database: crop
  user: postgres
  password: postgrespw
  #是否显示sql语句
  showsql: true
  #连接池中idle态链接最大个数
  maxidle: 10
  #连接池最大打开连接数
  maxopen: 5
